{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: task-aura
    environment: {{ .Values.global.environment }}
{{- end }}
